project_name: binbash
short_name: bb

primary_region: us-east-1
secondary_region: us-west-2

organization:
  accounts:
    management:
      email: aws@binbash.com
      id: 111111111111
    security:
      email: aws+security@binbash.com
    shared:
      email: aws+shared@binbash.com
  organizational_units:
  - name: security
    accounts:
    - security
  - name: shared
    accounts:
    - shared
  
users:
  

execution:
  enable_mfa: true
